stages:
- build
- test
- deploy

lint:
  image: nikolaik/python-nodejs:latest
  stage: test
  allow_failure: true
  script:
    - yarn
    - yarn lint
  cache:
    paths:
    - node_modules

build:
  image: nikolaik/python-nodejs:latest
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  cache:
    paths:
    - node_modules
    - .cache

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  dependencies: ["build"]
  script:
    - mv dist public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
